site_name: Galaxy Tool Dev
pages:
- [index.md, Creating Galaxy tools and workflows]
- [01_Galaxy.md, Introduction, Tutorials]
- [01_GCE.md, Introduction, Google Compute Engine]
- [02_Docker.md, Development, Docker]
- [02_ToolWrapper.md, Development, Tool Wrapper Syntax]
- [02_Examples.md, Development, Working With Examples]
- [05_ToolDev.md, Development, Tool Development]
- [06_Submitting.md, Submitting, Submitting Code]
- [07_Advanced.md, Advanced, Advanced]
imports:
-
    file: planemo/docs/commands/docker_build.rst
    name: PLANEMO_DOCKER
    head_trim: 6
-
    file: planemo/docs/_writing_parameters.rst
    name: WRITING_PARAMS
    head_trim: 6
templates:
- 03_Docker.md
- 05_ToolDev.md
